### PR TITLE
initial pass at correcting connection issues, introduce more toolbar ico...

### PR DESCRIPTION
**Pull request by seandepagnier**
...ns

### CODE REVIEW

**Comment by rgleason** [comment]
Good idea

**Comment by goodanchorage** [comment]
Clever handling of online/offline/busy states. Thank you!

**Comment by seandepagnier** [comment]
It's not really perfect, feel free to change it, just a start.

I will continue testing and try for more improvements.

**Comment by jeffblackb** [comment]
Let me preface with the fact that I could not have written it and I really like the way it is starting to work. What I am good at is breaking things. If the plugin is on and working (green anchor), followed by turning off internet connection, all the already downloaded info remains, but any attempt to right click on a new marker to get info hangs like before. Perhaps some sort of check for internet before attempting? Like I said, I don't know how to write the code, I just try to break it.

**Comment by goodanchorage** [comment]
It's all good Jeff. Any contribution is welcome. I added your observation
to one of the bug reports:

https://github.com/goodanchorage/goodanchorage_pi/issues/9

Thanks!
Dmitry

**Pull request merged**
